// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Count.proto

package com.superh.hz.bigdata.api.hbase.tool.coprocessor;

public final class CountProtos {
  private CountProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CountRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string count_flag = 1;
    /**
     * <code>required string count_flag = 1;</code>
     *
     * <pre>
     * 统计标记
     * </pre>
     */
    boolean hasCountFlag();
    /**
     * <code>required string count_flag = 1;</code>
     *
     * <pre>
     * 统计标记
     * </pre>
     */
    java.lang.String getCountFlag();
    /**
     * <code>required string count_flag = 1;</code>
     *
     * <pre>
     * 统计标记
     * </pre>
     */
    com.google.protobuf.ByteString
        getCountFlagBytes();
  }
  /**
   * Protobuf type {@code proto.CountRequest}
   */
  public static final class CountRequest extends
      com.google.protobuf.GeneratedMessage
      implements CountRequestOrBuilder {
    // Use CountRequest.newBuilder() to construct.
    private CountRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CountRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CountRequest defaultInstance;
    public static CountRequest getDefaultInstance() {
      return defaultInstance;
    }

    public CountRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CountRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              countFlag_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.internal_static_proto_CountRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.internal_static_proto_CountRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest.class, com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<CountRequest> PARSER =
        new com.google.protobuf.AbstractParser<CountRequest>() {
      public CountRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CountRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CountRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string count_flag = 1;
    public static final int COUNT_FLAG_FIELD_NUMBER = 1;
    private java.lang.Object countFlag_;
    /**
     * <code>required string count_flag = 1;</code>
     *
     * <pre>
     * 统计标记
     * </pre>
     */
    public boolean hasCountFlag() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string count_flag = 1;</code>
     *
     * <pre>
     * 统计标记
     * </pre>
     */
    public java.lang.String getCountFlag() {
      java.lang.Object ref = countFlag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          countFlag_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string count_flag = 1;</code>
     *
     * <pre>
     * 统计标记
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCountFlagBytes() {
      java.lang.Object ref = countFlag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        countFlag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      countFlag_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCountFlag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getCountFlagBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getCountFlagBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest)) {
        return super.equals(obj);
      }
      com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest other = (com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest) obj;

      boolean result = true;
      result = result && (hasCountFlag() == other.hasCountFlag());
      if (hasCountFlag()) {
        result = result && getCountFlag()
            .equals(other.getCountFlag());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCountFlag()) {
        hash = (37 * hash) + COUNT_FLAG_FIELD_NUMBER;
        hash = (53 * hash) + getCountFlag().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.CountRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.internal_static_proto_CountRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.internal_static_proto_CountRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest.class, com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest.Builder.class);
      }

      // Construct using com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        countFlag_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.internal_static_proto_CountRequest_descriptor;
      }

      public com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest getDefaultInstanceForType() {
        return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest.getDefaultInstance();
      }

      public com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest build() {
        com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest buildPartial() {
        com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest result = new com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.countFlag_ = countFlag_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest) {
          return mergeFrom((com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest other) {
        if (other == com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest.getDefaultInstance()) return this;
        if (other.hasCountFlag()) {
          bitField0_ |= 0x00000001;
          countFlag_ = other.countFlag_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCountFlag()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string count_flag = 1;
      private java.lang.Object countFlag_ = "";
      /**
       * <code>required string count_flag = 1;</code>
       *
       * <pre>
       * 统计标记
       * </pre>
       */
      public boolean hasCountFlag() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string count_flag = 1;</code>
       *
       * <pre>
       * 统计标记
       * </pre>
       */
      public java.lang.String getCountFlag() {
        java.lang.Object ref = countFlag_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          countFlag_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string count_flag = 1;</code>
       *
       * <pre>
       * 统计标记
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCountFlagBytes() {
        java.lang.Object ref = countFlag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          countFlag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string count_flag = 1;</code>
       *
       * <pre>
       * 统计标记
       * </pre>
       */
      public Builder setCountFlag(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        countFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string count_flag = 1;</code>
       *
       * <pre>
       * 统计标记
       * </pre>
       */
      public Builder clearCountFlag() {
        bitField0_ = (bitField0_ & ~0x00000001);
        countFlag_ = getDefaultInstance().getCountFlag();
        onChanged();
        return this;
      }
      /**
       * <code>required string count_flag = 1;</code>
       *
       * <pre>
       * 统计标记
       * </pre>
       */
      public Builder setCountFlagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        countFlag_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.CountRequest)
    }

    static {
      defaultInstance = new CountRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.CountRequest)
  }

  public interface CountResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 count_value = 1;
    /**
     * <code>required int64 count_value = 1;</code>
     *
     * <pre>
     * 统计结果
     * </pre>
     */
    boolean hasCountValue();
    /**
     * <code>required int64 count_value = 1;</code>
     *
     * <pre>
     * 统计结果
     * </pre>
     */
    long getCountValue();
  }
  /**
   * Protobuf type {@code proto.CountResponse}
   */
  public static final class CountResponse extends
      com.google.protobuf.GeneratedMessage
      implements CountResponseOrBuilder {
    // Use CountResponse.newBuilder() to construct.
    private CountResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CountResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CountResponse defaultInstance;
    public static CountResponse getDefaultInstance() {
      return defaultInstance;
    }

    public CountResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CountResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              countValue_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.internal_static_proto_CountResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.internal_static_proto_CountResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.class, com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<CountResponse> PARSER =
        new com.google.protobuf.AbstractParser<CountResponse>() {
      public CountResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CountResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CountResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 count_value = 1;
    public static final int COUNT_VALUE_FIELD_NUMBER = 1;
    private long countValue_;
    /**
     * <code>required int64 count_value = 1;</code>
     *
     * <pre>
     * 统计结果
     * </pre>
     */
    public boolean hasCountValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 count_value = 1;</code>
     *
     * <pre>
     * 统计结果
     * </pre>
     */
    public long getCountValue() {
      return countValue_;
    }

    private void initFields() {
      countValue_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCountValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, countValue_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, countValue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse)) {
        return super.equals(obj);
      }
      com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse other = (com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse) obj;

      boolean result = true;
      result = result && (hasCountValue() == other.hasCountValue());
      if (hasCountValue()) {
        result = result && (getCountValue()
            == other.getCountValue());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasCountValue()) {
        hash = (37 * hash) + COUNT_VALUE_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getCountValue());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.CountResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.internal_static_proto_CountResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.internal_static_proto_CountResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.class, com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.Builder.class);
      }

      // Construct using com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        countValue_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.internal_static_proto_CountResponse_descriptor;
      }

      public com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse getDefaultInstanceForType() {
        return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.getDefaultInstance();
      }

      public com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse build() {
        com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse buildPartial() {
        com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse result = new com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.countValue_ = countValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse) {
          return mergeFrom((com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse other) {
        if (other == com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.getDefaultInstance()) return this;
        if (other.hasCountValue()) {
          setCountValue(other.getCountValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCountValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 count_value = 1;
      private long countValue_ ;
      /**
       * <code>required int64 count_value = 1;</code>
       *
       * <pre>
       * 统计结果
       * </pre>
       */
      public boolean hasCountValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 count_value = 1;</code>
       *
       * <pre>
       * 统计结果
       * </pre>
       */
      public long getCountValue() {
        return countValue_;
      }
      /**
       * <code>required int64 count_value = 1;</code>
       *
       * <pre>
       * 统计结果
       * </pre>
       */
      public Builder setCountValue(long value) {
        bitField0_ |= 0x00000001;
        countValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 count_value = 1;</code>
       *
       * <pre>
       * 统计结果
       * </pre>
       */
      public Builder clearCountValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        countValue_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.CountResponse)
    }

    static {
      defaultInstance = new CountResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.CountResponse)
  }

  /**
   * Protobuf service {@code proto.CountService}
   */
  public static abstract class CountService
      implements com.google.protobuf.Service {
    protected CountService() {}

    public interface Interface {
      /**
       * <code>rpc count(.proto.CountRequest) returns (.proto.CountResponse);</code>
       */
      public abstract void count(
          com.google.protobuf.RpcController controller,
          com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest request,
          com.google.protobuf.RpcCallback<com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new CountService() {
        @java.lang.Override
        public  void count(
            com.google.protobuf.RpcController controller,
            com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest request,
            com.google.protobuf.RpcCallback<com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse> done) {
          impl.count(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.count(controller, (com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc count(.proto.CountRequest) returns (.proto.CountResponse);</code>
     */
    public abstract void count(
        com.google.protobuf.RpcController controller,
        com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest request,
        com.google.protobuf.RpcCallback<com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.count(controller, (com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest)request,
            com.google.protobuf.RpcUtil.<com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void count(
          com.google.protobuf.RpcController controller,
          com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest request,
          com.google.protobuf.RpcCallback<com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.class,
            com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse count(
          com.google.protobuf.RpcController controller,
          com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse count(
          com.google.protobuf.RpcController controller,
          com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.superh.hz.bigdata.api.hbase.tool.coprocessor.CountProtos.CountResponse.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:proto.CountService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CountRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_CountRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CountResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_CountResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Count.proto\022\005proto\"\"\n\014CountRequest\022\022\n\n" +
      "count_flag\030\001 \002(\t\"$\n\rCountResponse\022\023\n\013cou" +
      "nt_value\030\001 \002(\0032B\n\014CountService\0222\n\005count\022" +
      "\023.proto.CountRequest\032\024.proto.CountRespon" +
      "seBG\n0com.superh.hz.bigdata.api.hbase.to" +
      "ol.coprocessorB\013CountProtosH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_CountRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_CountRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_CountRequest_descriptor,
              new java.lang.String[] { "CountFlag", });
          internal_static_proto_CountResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_CountResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_CountResponse_descriptor,
              new java.lang.String[] { "CountValue", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
